services:
  - type: web
    name: shree-rr-trading-company-payroll
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
    domains:
      - shreerrtradingcompany.com
      - www.shreerrtradingcompany.com
